### ISSUE TITLE
Feature: User can search for up to 2 movies

### ISSUE THREAD

**Issue by JoeDeiRossi** [JoeDeiRossi/ajax-project#1]
## 📐 Functionality

The user will be able to type in titles of one or two movies and view up to five results for each search.

## ✅ Task List

- [x] Create the HTML/CSS for the home page based on the Figma template.
- [x] Add an event listener to each search button for click events.
- [x] In the event listener, open an ajax request to the movie search url of the TMDB API.
- [x] Display the first five results to the user and remove the search button.
- **Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
