### ISSUE TITLE
Feature: User can view and select from 2 separate lists of results

### ISSUE THREAD

**Issue by JoeDeiRossi** [JoeDeiRossi/ajax-project#2]
## 📐 Functionality

After searching, the user can view five results for each search and select a result to be taken to the movie's cast and crew.

## ✅ Task List

- [x] Add an event listener for each search result for click events.
- [x] When a movie is clicked, open an ajax request to the movie credits url using the id of the clicked movie.
- [ ] When a movie is clicked, check to see if 2 movies are selected. If so, make the Compare button active.
- [x] Store the cast and crew arrays from the response locally for later use.
- [ ] Update the screen to display dropdowns for the cast and crew.
- **Clean Up**
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
