### ISSUE TITLE
Feature: User can view the cast/crew of each movie

### ISSUE THREAD

**Issue by JoeDeiRossi** [JoeDeiRossi/ajax-project#3]
## 📐 Functionality

When the user clicks a dropdown for cast or crew of a movie, the appropriate list(s) of people will be displayed.

## ✅ Task List

- [ ] Add event listeners for click events on the cast and crew dropdowns.
- [ ] When a dropdown is expanded by the user, display the full cast or crew using the previously stored response data.
- **Clean Up**
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
