### ISSUE TITLE
Feature: User can reset each search independently

### ISSUE THREAD

**Issue by JoeDeiRossi** [JoeDeiRossi/ajax-project#4]
## 📐 Functionality

Each movie search will operate independently and the user will be able to reset one of them without having to start over entirely

## ✅ Task List

- [ ] Add event listeners to the reset buttons for click events.
- [ ] When a reset button is clicked, clear whatever was previously on the matching search (movie search results, or cast/crew) and show the Search button again.
- [ ] When either reset button is clicked, clear the comparison area and deactivate the Compare button.
- **Clean Up**
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
