### ISSUE TITLE
Feature: User can find out if anyone worked on both films

### ISSUE THREAD

**Issue by JoeDeiRossi** [JoeDeiRossi/ajax-project#5]
## 📐 Functionality

Once two movies have been selected, the Compare button will become available to the user. Clicking this button will display a new list at the bottom of the page with any cast/crew that worked on both movies.

## ✅ Task List

- [ ] Add an event listener to the Compare button and listen for click events.
- [ ] When the Compare button is clicked, loop through each movie's cast/crew arrays. Using their TMDB id numbers, check for any commonalities between movies.
- [ ] For each match, display their name and role/job at the bottom of the page in a new list
- **Clean Up**
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
